
### FICHIER TEST RISHI BONTEMPS
# Créer un projet
POST http://localhost:3000/Projects
Content-Type: application/json

{
  "name": "EVALUATION Finale RISHI BONTEMPS",
  "description": "Mon petit projet final pour optimisation base de donnée"
}


###
# Obtenir une liste de projets
GET http://localhost:3000/Projects


###
# Supprimer un projet
DELETE http://localhost:3000/Projects/6752d5e31999da4f3abc9f5e


###
# Modifier un projet
PUT http://localhost:3000/Projects/6752d66a1999da4f3abc9f64
Content-Type: application/json

{
  "name": "Modification réussite ",
  "description": "effectué"
}


###
# Créer une tâche
POST http://localhost:3000/taches
Content-Type: application/json

{
  "projectId": "egesgrvfrvwfsr848rgv2fe48s",
  "title": "Ma première mission",
  "dueDate": "2025-07-15"
}


###
# Obtenir une liste de tâches
GET http://localhost:3000/taches


###
# Supprimer une tâche
DELETE http://localhost:3000/taches/6752f9e475de22f6478e886d


###
# Modifier une tâche
PUT http://localhost:3000/taches/6752d66a1999da4f3abc9f64
Content-Type: application/json

{
  "title": "Modification russite",
  "dueDate": "2025-07-14"
}


###
# Récupérer tache avec l'id
GET http://localhost:3000/taches/6752d66a1999da4f3abc9f64